### PR TITLE
Weather-App

### PR DESCRIPTION
**Pull request by arikarim**
A Weather built with JavaScript, users can see the weather just by typing the city name.
It's a simple fetch function that grabs the API URL and brings back the data where it's been injected into the dom.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨

- Simple design, easy to use.

## However, there are some changes required 👀 🧰 🔨 🔧
- Please write a better PR description where you list the concepts you learned while working on this project.
- Please add some error handling to your async/await API function by using `try/catch`, to handle errors in case the API fails.
- Please add a toggle button to convert Celsius to Fahrenheit and vice-versa.
- Please modulate your code by separating DOM, API and App logic in different files, and including them with `import` and `export`
- Please make sure your `package.json` contains all the necessary scripts:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

***[OPTIONAL]***
- You may add a `loading` function to your API call while the information is returning from the API.
- You may detect the current geolocation of the user so their current weather is displayed automatically on page load.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making some of the changes requested. 
Let's make more changes requested.
- [ ] add error handling to your async/await API function using `try/catch` block
- [ ] add a toggle button to convert Celsius to Fahrenheit and vice-versa.
- [ ] separate DOM, API, and App logic
- [ ] fix linter errors

### Martin Afani
#### Slack: whiz25

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The codebase is clean. 💯
  - [x]  The project follows Git flow. 💯
  - [x] Implemented some of the previous feedback. 💯

- ### To Improve
  - [x] [MANDATORY] You should implement a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: you can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @arikarim  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
